[[mounts]]
"dest" = "/linux"
"dev" = "sda2"
"fs" = "ext4"

[[mounts]]
"dest" = "/linux/home"
"dev" = "sda3"
"fs" = "ext4"

[[run]]
"path" = "/home/init_sys.sh"
"args" = ["init_sys.sh"]

[init]
"root" = "/linux"
"path" = "/sbin/init"
"args" = ["init"]
