[toolchain]
channel = "nightly-2026-03-07"
profile = "minimal"
components = [
    "rustfmt",
    "clippy",
    "llvm-tools",
    "rust-src",
    "miri",
    "rust-analyzer",
]
targets = ["riscv64gc-unknown-none-elf", "loongarch64-unknown-none"]
