name = "sched-attr-test"
targets = ["riscv64", "loongarch64"]

[build]
workdir = "."
driver = "cargo"
args = ["build", "--release"]

[[artifacts]]
path = "target/${TARGET_TRIPLE}/release/sched-attr-test"
