#! Toml schema for platform configuration

# Basic information
# This section defines how to build Anemone kernel for the target platform.

[build]
# Name of the target platform, used for identification and will be embedded into kernel
name = "example-platform"
# Abbreviations for the platform, used for command line arguments and such.
abbrs = ["eg", "example"]
# Architecture of the target platform
# e.g., riscv64, x86_64, arm64, loongarch64
arch = "riscv64"
# Target triple for the compiler
# See conf/arch/[arch]/ for available target triples for each architecture
target = "riscv64-unknown-anemone-elf"
# Execution environment for the target platform
# This include BIOS, UEFI, SBI, UBoot, etc.
exec_env = "sbi"

[constants]
# Physical address where RAM starts
phys_ram_start = 0x80000000
# Maximum size of physical RAM supported by this platform
# This will be used when we do optimistic memory mapping during early boot.
max_phys_ram_size = 0x80000000
# Load address of the kernel in physical memory
kernel_la_base = 0x80200000
# Virtual address where the kernel is mapped during runtime
kernel_va_base = 0xffffffff80200000
# Maximum number of CPUs supported by this platform
max_cpus = 4
# Page frame section size as a power of 2 in megabytes.
frame_section_shift_mb = 7

# QEMU configuration
# This section defines how to run the target platform in QEMU,
# if applicable.
[qemu]
# QEMU binary to use
qemu = "qemu-system-riscv64"
# QEMU machine type
machine = "virt"
# CPU type, optional
cpu = "rv64"
# number of CPUs
smp = 4
# Amount of memory
memory = "512M"
# Platform firmware to use, optional
bios = "default"
# Additional QEMU arguments
args = [
    "-serial",
    "mon:stdio",
    "-device",
    "virtio-net-device,netdev=net0",
    "-netdev",
    "user,id=net0,hostfwd=tcp::2222-:22",
]

# Device Tree Blob configuration for the platform, optional
[dtb]
# Path to the generated DTB file
path = "arch/loongarch64/generated.dtb"
# Type of the DTB source, can be "file" or "qemu"
type = "file"
# Source of the DTB, ignored if type is not "file".
source = "arch/loongarch64/dtb/virt-la64.dts"