[build]
arch = "riscv64"
exec_env = "sbi"

[constants]
phys_ram_start = 0x80000000
max_phys_ram_size = 0x80000000      # 2GB
kernel_la_base = 0x80200000
kernel_va_base = 0xffffffff80200000
max_phys_cpu_id = 15
frame_section_shift_mb = 7

[qemu]
machine = "virt"
cpu = "rv64"
smp = 1
memory = "1G"
bios = "default"
args = [
    "-rtc",
    "base=utc",
    "-device",
    "virtio-net-device,netdev=net",
    "-netdev",
    "user,id=net",
    "-accel",
    "tcg,thread=multi",

    "-no-reboot",
]

[[qemu.bind]]
name = "kernel-image"
template = ["-kernel", "{{}}"]

[[qemu.bind]]
name = "disk-x0"
template = [
    "-drive",
    "file={{}},format=raw,if=none,id=x0",
    "-device",
    "virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0",
]

[[qemu.bind]]
name = "disk-x1"
template = [
    "-drive",
    "file={{}},format=raw,if=none,id=x1",
    "-device",
    "virtio-blk-device,drive=x1,bus=virtio-mmio-bus.1",
]

[dtb]
source = "conf/platforms/qemu-virt-rv64.dts"
delivery = "firmware"
authority = "provider-derived"
provider = "qemu"
