[build]
name = "qemu-virt-la64"
abbrs = ["la", "la64", "loongarch", "loongarch64"]
arch = "loongarch64"
exec_env = "sbi"

[constants]
phys_ram_start = 0x80000000
max_phys_ram_size = 0x80000000      # 2GB
kernel_la_base = 0x80200000
kernel_va_base = 0xffffffff80200000
max_user_stack_size = 0x800000      # 8MB
init_user_stack_size = 0x4000       # 16KB
max_heap_size = 0x2000000000        # 128GB
max_cpus = 4
frame_section_shift_mb = 7

[qemu]
qemu = "qemu-system-loongarch64"
machine = "virt"
# cpu = default
smp = 4
memory = "4G"
args = ["-nographic", "-serial", "mon:stdio"]


[dtb]
path = "arch/loongarch64/generated.dtb"
type = "qemu"
