[build]
name = "qemu-virt-rv64"
abbrs = ["rv", "rv64", "riscv", "riscv64"]
arch = "riscv64"
target = "riscv64-unknown-anemone-elf"
exec_env = "sbi"

[constants]
phys_ram_start = 0x80000000
max_phys_ram_size = 0x80000000      # 2GB
kernel_la_base = 0x80200000
kernel_va_base = 0xffffffff80200000
max_cpus = 14
frame_section_shift_mb = 7


[qemu]
qemu = "qemu-system-riscv64"
machine = "virt"
cpu = "rv64"
smp = 14
memory = "1G"
bios = "default"
args = [
    "-nographic",
    "-serial",
    "mon:stdio",
    "-rtc",
    "base=utc",
    "-device",
    "virtio-net-device,netdev=net",
    "-netdev",
    "user,id=net",

    # "-drive",
    # "file=rootfs-rv.img,format=raw,if=none,id=x0",
    # "-device",
    # "virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0",
    # "-no-reboot",
    # "-drive",
    # "file=disk.img,format=raw,if=none,id=x1",
    # "-device",
    # "virtio-blk-device,drive=x1,bus=virtio-mmio-bus.1",
]

[rootfs]
fstype = "ext4"
source = { type = "block", path = "/soc/virtio_mmio@10001000" }

[dtb]
path = "arch/riscv64/generated.dtb"
type = "qemu"
