[build]
arch = "loongarch64"
exec_env = "sbi"

[constants]
phys_ram_start = 0x80000000
max_phys_ram_size = 0x80000000      # 2GB
kernel_la_base = 0x80200000
kernel_va_base = 0xffffffff80200000
earlycon_reg = 0x1fe001e0
max_phys_cpu_id = 0
frame_section_shift_mb = 7

[qemu]
machine = "virt"
cpu = "la464"
smp = "1"
memory = "1G"
args = [
    "-rtc",
    "base=utc",
    "-accel",
    "tcg,thread=multi",
    "-no-reboot",
    "-device",
    "pcie-root-port,id=pcie.1,bus=pcie.0",
]

[[qemu.bind]]
name = "kernel-image"
optional = false
template = ["-kernel", "{{kernel-image}}"]

[[qemu.bind]]
name = "disk-x0"
optional = false
template = [
    "-drive",
    "file={{disk-x0}},format=raw,if=none,id=x0",
    "-device",
    "virtio-blk-pci-transitional,drive=x0,bus=pcie.0",
]

[[qemu.bind]]
name = "disk-x1"
optional = false
template = [
    "-drive",
    "file={{disk-x1}},format=raw,if=none,id=x1",
    "-device",
    "virtio-blk-pci-transitional,drive=x1,bus=pcie.0",
]

[dtb]
delivery = "embedded"
authority = "provider-derived"
provider = "qemu"
