[build]
name = "qemu-virt-la64"
abbrs = ["la", "la64", "loongarch", "loongarch64"]
arch = "loongarch64"
exec_env = "sbi"

[constants]
phys_ram_start = 0x80000000
max_phys_ram_size = 0x80000000      # 2GB
kernel_la_base = 0x80200000
kernel_va_base = 0xffffffff80200000
max_cpus = 4
frame_section_shift_mb = 7

[qemu]
qemu = "qemu-system-loongarch64"
machine = "virt"
smp = 4
memory = "4G"
# cpu = default
args = [
    "-nographic",
    "-serial",
    "mon:stdio",

    # "-no-reboot",
    # "-drive",
    # "file=sdcard-la.img,format=raw,if=none,id=x0",
    # "-device",
    # "virtio-blk-pci-transitional,drive=x0",
    # 
    # "-device",
    # "pcie-root-port,id=pcie.1,bus=pcie.0",
    # 
    # "-drive",
    # "file=build/rootfs/minimal/rootfs.img,format=raw,if=none,id=x1",
    # "-device",
    # "virtio-blk-pci-transitional,drive=x1,bus=pcie.1",
    
]

[rootfs]
fstype = "ext4"
source = { type = "block", path = "vdb" }


[dtb]
path = "arch/loongarch64/generated.dtb"
type = "qemu"
