[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
xshell = { path = "vendor/xshell" }
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
toml = { version = "0.9.11" }
clap = { version = "4.5.55", features = ["derive"] }
symtab = { path = "../../symtab", features = ["builder"] }
toml_edit = "0.25.4"
goblin = "0.10.5"
rustc-demangle = "0.1.27"
nemophila-wasm = { path = "../../anemone-kernel/crates/nemophila-wasm", default-features = false, features = ["extra-checks", "std"] }
wasmparser = "=0.244.0"
wit-component = "=0.244.0"
wit-parser = "=0.244.0"

[dev-dependencies]
wat = "=1.244.0"
