[build]
name = "anemone-bench-la64"
arch = "loongarch64"

[fs]
type = "folder"
fstype = "ext4"
extra-size = "64M"

[init]
path = "/sbin/busybox-init"

[[dirs]]
path = "/dev"

[[dirs]]
path = "/proc"

[[dirs]]
path = "/root"

[[dirs]]
path = "/run"

[[dirs]]
path = "/tmp"

[[apps]]
name = "busybox-init"
installed_dir = "/sbin"

[[apps]]
name = "anemone-bench"
installed_dir = "/bin"

[[apps]]
name = "perfctl"
installed_dir = "/bin"

[[apps]]
name = "shutdown"
installed_dir = "/bin"
