[build]
name = "command-driver-acceptance-la64"
arch = "loongarch64"

[fs]
type = "folder"
fstype = "ext4"

[init]
path = "/sbin/command-driver-test"

[[dirs]]
path = "/dev"

[[apps]]
name = "command-driver-test"
installed_dir = "/sbin"

[[apps]]
name = "command-c"
installed_dir = "/bin"

[[apps]]
name = "command-cpp"
installed_dir = "/bin"
