[build]
name = "log-acceptance-la64"
arch = "loongarch64"

[fs]
type = "folder"
fstype = "ext4"

[init]
path = "/sbin/log-test"

[[dirs]]
path = "/dev"

[[apps]]
name = "log-test"
installed_dir = "/sbin"
