[build]
name = "minimal-la"
arch = "loongarch64"

[fs]
fstype = "ext4"
base = "etc/base-la"

[init]
path = "/sbin/init"

[[apps]]
name = "init"
installed_dir = "/sbin"

[[apps]]
name = "user-test"
installed_dir = "/bin"

# [[apps]]
# name = "float-test"
# installed_dir = "/bin"
# 
# [[apps]]
# name = "shm-test"
# installed_dir = "/bin"
# 
# [[apps]]
# name = "mmap-test"
# installed_dir = "/bin"
# 
# [[apps]]
# name = "pg-test"
# installed_dir = "/bin"
# 
# [[apps]]
# name = "pthread-create-stress"
# installed_dir = "/bin"

[[files]]
source = "anemone-apps/user-test/staged/loongarch/mke2fs"
installed_path = "/fixtures/user-test/tools/mke2fs"
