[build]
name = "pretest-la64"
arch = "loongarch64"

[fs]
type = "folder"
fstype = "ext4"
base = "conf/rootfs/pretest-la64-base"

[init]
path = "/sbin/init"

[[dirs]]
path = "/dev"

[[dirs]]
path = "/mnt"

[[dirs]]
path = "/proc"

[[dirs]]
path = "/tmp"

[[apps]]
name = "init"
installed_dir = "/sbin"

[[apps]]
name = "user-test"
installed_dir = "/bin"

[[apps]]
name = "socket-r1-oracle"
installed_dir = "/bin"

[[apps]]
name = "tcp-r0-oracle"
installed_dir = "/bin"

[[apps]]
name = "userptr"
installed_dir = "/bin"

[[apps]]
name = "fcntl-test"
installed_dir = "/bin"

# [[apps]]
# name = "ioctl-test"
# installed_dir = "/bin"

# [[apps]]
# name = "epoll-test"
# installed_dir = "/bin"
#
# [[apps]]
# name = "flock-test"
# installed_dir = "/bin"
#
[[apps]]
name = "socket-test"
installed_dir = "/bin"

[[apps]]
name = "rust-command-test"
installed_dir = "/bin"

# [[apps]]
# name = "fair-test"
# installed_dir = "/bin"

# [[apps]]
# name = "float-test"
# installed_dir = "/bin"
# 
# [[apps]]
# name = "shm-test"
# installed_dir = "/bin"
# 
# [[apps]]
# name = "mmap-test"
# installed_dir = "/bin"
# 
# [[apps]]
# name = "pg-test"
# installed_dir = "/bin"
# 
# [[apps]]
# name = "pthread-create-stress"
# installed_dir = "/bin"

[[files]]
source = "anemone-apps/user-test/staged/loongarch/mke2fs"
installed_path = "/fixtures/user-test/tools/mke2fs"
