[build]
name = "static-sysfs-acceptance-la64"
arch = "loongarch64"

[fs]
type = "folder"
fstype = "ext4"

[init]
path = "/sbin/static-sysfs-test"

[[dirs]]
path = "/sys"

[[dirs]]
path = "/sys2"

[[dirs]]
path = "/proc"

[[apps]]
name = "static-sysfs-test"
installed_dir = "/sbin"
