#! This manifest describes the minimal rootfs configuration for Anemone.

[build]
# Generated image name.
name = "2k1000"
# Target architecture for the generated image. This determines how user-space binaries are built.
arch = "loongarch64"

[fs]
# Filesystem type to use.
fstype = "ext4"
base = "conf/rootfs/2k1000/base"
type = "folder"
extra-size = "256M"

# Init process configuration. This will be written into /.anemone/init and used by kernel to launch the init process.
[init]
path = "/sbin/board-init"

[[apps]]
name = "board-init"
installed_dir = "/sbin"

[[apps]]
name = "shutdown"
installed_dir = "/sbin"
