#pragma once

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define STDIN_FILENO 0

#define STDOUT_FILENO 1

#define STDERR_FILENO 2

#define SEEK_SET 0

#define SEEK_CUR 1

#define SEEK_END 2

#define SEEK_DATA 3

#define SEEK_HOLE 4

#define O_RDONLY 0

#define O_WRONLY 1

#define O_RDWR 2

#define O_ACCMODE 3

#define O_CREAT 64

#define O_EXCL 128

#define O_NOCTTY 256

#define O_TRUNC 512

#define O_APPEND 1024

#define O_NONBLOCK 2048

#define O_NDELAY O_NONBLOCK

#define O_DSYNC 4096

#define O_ASYNC 8192

#define O_DIRECT 16384

#define O_LARGEFILE 32768

#define O_DIRECTORY 65536

#define O_NOFOLLOW 131072

#define O_NOATIME 262144

#define O_CLOEXEC 524288

#define O_SYNC 1052672

#define O_PATH 2097152

#define O_TMPFILE 4259840

#define S_IFMT 61440

#define S_IFSOCK 49152

#define S_IFLNK 40960

#define S_IFREG 32768

#define S_IFBLK 24576

#define S_IFDIR 16384

#define S_IFCHR 8192

#define S_IFIFO 4096

#define S_ISUID 2048

#define S_ISGID 1024

#define S_ISVTX 512

#define S_IRWXU 448

#define S_IRUSR 256

#define S_IWUSR 128

#define S_IXUSR 64

#define S_IRWXG 56

#define S_IRGRP 32

#define S_IWGRP 16

#define S_IXGRP 8

#define S_IRWXO 7

#define S_IROTH 4

#define S_IWOTH 2

#define S_IXOTH 1

#define AT_FDCWD -100

#define AT_SYMLINK_NOFOLLOW 256

#define AT_REMOVEDIR 512

#define AT_SYMLINK_FOLLOW 1024

#define AT_NO_AUTOMOUNT 2048

#define AT_EMPTY_PATH 4096

#define AT_STATX_SYNC_TYPE 24576

#define AT_STATX_SYNC_AS_STAT 0

#define AT_STATX_FORCE_SYNC 8192

#define AT_STATX_DONT_SYNC 16384

#define TYPE 1

#define MODE 2

#define NLINK 4

#define UID 8

#define GID 16

#define ATIME 32

#define MTIME 64

#define CTIME 128

#define INO 256

#define SIZE 512

#define BLOCKS 1024

#define BASIC_STATS 2047

#define BTIME 2048

#define MNT_ID 4096

#define DIOALIGN 8192

#define ALL 16383

#define ATTRIBUTE_COMPRESSED 4

#define ATTRIBUTE_IMMUTABLE 16

#define ATTRIBUTE_APPEND 32

#define ATTRIBUTE_NODUMP 64

#define ATTRIBUTE_ENCRYPTED 2048

#define ATTRIBUTE_AUTOMOUNT 4096

#define ATTRIBUTE_MOUNT_ROOT 8192

#define ATTRIBUTE_VERITY 1048576

#define ATTRIBUTE_DAX 2097152

#define DT_UNKNOWN 0

#define DT_FIFO 1

#define DT_CHR 2

#define DT_DIR 4

#define DT_BLK 6

#define DT_REG 8

#define DT_LNK 10

#define DT_SOCK 12

#define DT_WHT 14

/**
 * The Linux kernel actually does not define a maximum syscall number,
 * but it's obvious that syscall numbers won't exceed this value minus one, on
 * any architecture.
 *
 * Anemone defines its own syscall number starting from this value.
 */
#define LINUX_SYSNO_MAX 512

/**
 * The syscall number where Anemone-specific syscalls start.
 *
 * Currently unused.
 */
#define SYS_ANEMONE_START (LINUX_SYSNO_MAX + 0)

/**
 * Syscall (Linux or Anemone-native) numbers will not exceed this value minus
 * one.
 */
#define ANEMONE_SYSNO_MAX 1024

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_GETCWD 17
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_GETCWD 17
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_DUP 23
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_DUP 23
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_DUP3 24
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_DUP3 24
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_MKDIRAT 34
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_MKDIRAT 34
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_UNLINKAT 35
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_UNLINKAT 35
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_UMOUNT2 39
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_UMOUNT2 39
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_MOUNT 40
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_MOUNT 40
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_CHDIR 49
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_CHDIR 49
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_CHROOT 51
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_CHROOT 51
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_OPENAT 56
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_OPENAT 56
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_CLOSE 57
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_CLOSE 57
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_GETDENTS64 61
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_GETDENTS64 61
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_READ 63
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_READ 63
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_WRITE 64
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_WRITE 64
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_FSTAT 80
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_FSTAT 80
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_EXIT 93
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_EXIT 93
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_SCHED_YIELD 124
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_SCHED_YIELD 124
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_UNAME 160
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_UNAME 160
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_GETPID 172
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_GETPID 172
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_GETPPID 173
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_GETPPID 173
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_CLONE 220
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_CLONE 220
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_EXECVE 221
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_EXECVE 221
#endif

#if defined(__ANEMONE_ARCH_RISCV64__)
#define SYS_BRK 214
#endif

#if defined(__ANEMONE_ARCH_LOONGARCH64__)
#define SYS_BRK 214
#endif

#define SYS_DBG_PRINT (SYS_ANEMONE_START + 0)

/**
 * Type representing errno values.
 *
 * This type always wraps a positive integer, and the convention is that
 * a function should return a '-errno' value to indicate an error, and return a
 * non-negative value to indicate success.
 */
typedef int32_t Errno;

/**
 * Linux kernel actually does not define a maximum errno value,
 * but we define one here for reference.
 *
 * And it is indeed very unlikely that errno values will exceed this value.
 */
#define LINUX_ERRNO_MAX 65535

/**
 * Operation not permitted
 */
#define EPERM 1

/**
 * No such file or directory
 */
#define ENOENT 2

/**
 * No such process
 */
#define ESRCH 3

/**
 * Interrupted system call
 */
#define EINTR 4

/**
 * I/O error
 */
#define EIO 5

/**
 * No such device or address
 */
#define ENXIO 6

/**
 * Argument list too long
 */
#define E2BIG 7

/**
 * Exec format error
 */
#define ENOEXEC 8

/**
 * Bad file number
 */
#define EBADF 9

/**
 * No child processes
 */
#define ECHILD 10

/**
 * Try again
 */
#define EAGAIN 11

/**
 * Out of memory
 */
#define ENOMEM 12

/**
 * Permission denied
 */
#define EACCES 13

/**
 * Bad address
 */
#define EFAULT 14

/**
 * Block device required
 */
#define ENOTBLK 15

/**
 * Device or resource busy
 */
#define EBUSY 16

/**
 * File exists
 */
#define EEXIST 17

/**
 * Cross-device link
 */
#define EXDEV 18

/**
 * No such device
 */
#define ENODEV 19

/**
 * Not a directory
 */
#define ENOTDIR 20

/**
 * Is a directory
 */
#define EISDIR 21

/**
 * Invalid argument
 */
#define EINVAL 22

/**
 * File table overflow
 */
#define ENFILE 23

/**
 * Too many open files
 */
#define EMFILE 24

/**
 * Not a typewriter
 */
#define ENOTTY 25

/**
 * Text file busy
 */
#define ETXTBSY 26

/**
 * File too large
 */
#define EFBIG 27

/**
 * No space left on device
 */
#define ENOSPC 28

/**
 * Illegal seek
 */
#define ESPIPE 29

/**
 * Read-only file system
 */
#define EROFS 30

/**
 * Too many links
 */
#define EMLINK 31

/**
 * Broken pipe
 */
#define EPIPE 32

/**
 * Math argument out of domain of func
 */
#define EDOM 33

/**
 * Math result not representable
 */
#define ERANGE 34

/**
 * Resource deadlock would occur
 */
#define EDEADLK 35

/**
 * File name too long
 */
#define ENAMETOOLONG 36

/**
 * No record locks available
 */
#define ENOLCK 37

/**
 * This error code is special: arch syscall entry code will return
 * -ENOSYS if users try to call a syscall that doesn't exist.  To keep
 * failures of syscalls that really do exist distinguishable from
 * failures due to attempts to use a nonexistent syscall, syscall
 * implementations should refrain from returning -ENOSYS.
 *
 * Invalid system call number
 */
#define ENOSYS 38

/**
 * Directory not empty
 */
#define ENOTEMPTY 39

/**
 * Too many symbolic links encountered
 */
#define ELOOP 40

/**
 * Operation would block
 */
#define EWOULDBLOCK EAGAIN

/**
 * No message of desired type
 */
#define ENOMSG 42

/**
 * Identifier removed
 */
#define EIDRM 43

/**
 * Channel number out of range
 */
#define ECHRNG 44

/**
 * Level 2 not synchronized
 */
#define EL2NSYNC 45

/**
 * Level 3 halted
 */
#define EL3HLT 46

/**
 * Level 3 reset
 */
#define EL3RST 47

/**
 * Link number out of range
 */
#define ELNRNG 48

/**
 * Protocol driver not attached
 */
#define EUNATCH 49

/**
 * No CSI structure available
 */
#define ENOCSI 50

/**
 * Level 2 halted
 */
#define EL2HLT 51

/**
 * Invalid exchange
 */
#define EBADE 52

/**
 * Invalid request descriptor
 */
#define EBADR 53

/**
 * Exchange full
 */
#define EXFULL 54

/**
 * No anode
 */
#define ENOANO 55

/**
 * Invalid request code
 */
#define EBADRQC 56

/**
 * Invalid slot
 */
#define EBADSLT 57

/**
 * Bad font file format
 */
#define EBFONT 59

/**
 * Device not a stream
 */
#define ENOSTR 60

/**
 * No data available
 */
#define ENODATA 61

/**
 * Timer expired
 */
#define ETIME 62

/**
 * Out of streams resources
 */
#define ENOSR 63

/**
 * Machine is not on the network
 */
#define ENONET 64

/**
 * Package not installed
 */
#define ENOPKG 65

/**
 * Object is remote
 */
#define EREMOTE 66

/**
 * Link has been severed
 */
#define ENOLINK 67

/**
 * Advertise error
 */
#define EADV 68

/**
 * Srmount error
 */
#define ESRMNT 69

/**
 * Communication error on send
 */
#define ECOMM 70

/**
 * Protocol error
 */
#define EPROTO 71

/**
 * Multihop attempted
 */
#define EMULTIHOP 72

/**
 * RFS specific error
 */
#define EDOTDOT 73

/**
 * Not a data message
 */
#define EBADMSG 74

/**
 * Value too large for defined data type
 */
#define EOVERFLOW 75

/**
 * Name not unique on network
 */
#define ENOTUNIQ 76

/**
 * File descriptor in bad state
 */
#define EBADFD 77

/**
 * Remote address changed
 */
#define EREMCHG 78

/**
 * Can not access a needed shared library
 */
#define ELIBACC 79

/**
 * Accessing a corrupted shared library
 */
#define ELIBBAD 80

/**
 * .lib section in a.out corrupted
 */
#define ELIBSCN 81

/**
 * Attempting to link in too many shared libraries
 */
#define ELIBMAX 82

/**
 * Cannot exec a shared library directly
 */
#define ELIBEXEC 83

/**
 * Illegal byte sequence
 */
#define EILSEQ 84

/**
 * Interrupted system call should be restarted
 */
#define ERESTART 85

/**
 * Streams pipe error
 */
#define ESTRPIPE 86

/**
 * Too many users
 */
#define EUSERS 87

/**
 * Socket operation on non-socket
 */
#define ENOTSOCK 88

/**
 * Destination address required
 */
#define EDESTADDRREQ 89

/**
 * Message too long
 */
#define EMSGSIZE 90

/**
 * Protocol wrong type for socket
 */
#define EPROTOTYPE 91

/**
 * Protocol not available
 */
#define ENOPROTOOPT 92

/**
 * Protocol not supported
 */
#define EPROTONOSUPPORT 93

/**
 * Socket type not supported
 */
#define ESOCKTNOSUPPORT 94

/**
 * Operation not supported on transport endpoint
 */
#define EOPNOTSUPP 95

/**
 * Protocol family not supported
 */
#define EPFNOSUPPORT 96

/**
 * Address family not supported by protocol
 */
#define EAFNOSUPPORT 97

/**
 * Address already in use
 */
#define EADDRINUSE 98

/**
 * Cannot assign requested address
 */
#define EADDRNOTAVAIL 99

/**
 * Network is down
 */
#define ENETDOWN 100

/**
 * Network is unreachable
 */
#define ENETUNREACH 101

/**
 * Network dropped connection because of reset
 */
#define ENETRESET 102

/**
 * Software caused connection abort
 */
#define ECONNABORTED 103

/**
 * Connection reset by peer
 */
#define ECONNRESET 104

/**
 * No buffer space available
 */
#define ENOBUFS 105

/**
 * Transport endpoint is already connected
 */
#define EISCONN 106

/**
 * Transport endpoint is not connected
 */
#define ENOTCONN 107

/**
 * Cannot send after transport endpoint shutdown
 */
#define ESHUTDOWN 108

/**
 * Too many references: cannot splice
 */
#define ETOOMANYREFS 109

/**
 * Connection timed out
 */
#define ETIMEDOUT 110

/**
 * Connection refused
 */
#define ECONNREFUSED 111

/**
 * Host is down
 */
#define EHOSTDOWN 112

/**
 * No route to host
 */
#define EHOSTUNREACH 113

/**
 * Operation already in progress
 */
#define EALREADY 114

/**
 * Operation now in progress
 */
#define EINPROGRESS 115

/**
 * Stale file handle
 */
#define ESTALE 116

/**
 * Structure needs cleaning
 */
#define EUCLEAN 117

/**
 * Not a XENIX named type file
 */
#define ENOTNAM 118

/**
 * No XENIX semaphores available
 */
#define ENAVAIL 119

/**
 * Is a named type file
 */
#define EISNAM 120

/**
 * Remote I/O error
 */
#define EREMOTEIO 121

/**
 * Quota exceeded
 */
#define EDQUOT 122

/**
 * No medium found
 */
#define ENOMEDIUM 123

/**
 * Wrong medium type
 */
#define EMEDIUMTYPE 124

/**
 * Operation Canceled
 */
#define ECANCELED 125

/**
 * Required key not available
 */
#define ENOKEY 126

/**
 * Key has expired
 */
#define EKEYEXPIRED 127

/**
 * Key has been revoked
 */
#define EKEYREVOKED 128

/**
 * Key was rejected by service
 */
#define EKEYREJECTED 129

/**
 * Owner died
 */
#define EOWNERDEAD 130

/**
 * State not recoverable
 */
#define ENOTRECOVERABLE 131

/**
 * Operation not possible due to RF-kill
 */
#define ERFKILL 132

/**
 * Memory page has hardware error
 */
#define EHWPOISON 133

#define ERR_ANEMONE_START (LINUX_ERRNO_MAX + 1)
